# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=50)),
                ('meta_value', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='post', max_length=50),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
